
JARFILEPATH = "`pwd`"/target/hw1.1-0.0.1-SNAPSHOT-jar-with-dependencies.jar
FILEPATH = "`pwd`"/*.csv

#
# the default make target entry
#


default: 
	mvn install

local:
	java -jar $(JARFILEPATH) $(FILEPATH)

