

#
# the default make target entry
#


default: 
	mvn install
local:
	java -jar ./target/hw3-0.0.1-jar-with-dependencies.jar ./input ./output


# for page rank input , put all .bz2 files in input folder